In [130]:
import numpy as np

array1 = np.array(range(30))
print(array1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [131]:
r_array1 = array1.reshape(5,6,order='F')
print(r_array1)

[[ 0  5 10 15 20 25]
 [ 1  6 11 16 21 26]
 [ 2  7 12 17 22 27]
 [ 3  8 13 18 23 28]
 [ 4  9 14 19 24 29]]


In [132]:
print('The value is: ', r_array1[np.where(r_array1%6 == 1)], 'and the index of each value', np.argwhere(r_array1%6 == 1))

The value is:  [25  1  7 13 19] and the index of each value [[0 5]
 [1 0]
 [2 1]
 [3 2]
 [4 3]]
